# Generated by Django 4.2 on 2023-04-30 16:56

import admin_portal.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('description', models.TextField(max_length=2500)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=admin_portal.models.unique_car_image)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_of_cars', to='admin_portal.car')),
            ],
        ),
    ]
