# Generated by Django 4.2 on 2023-04-30 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_portal', '0002_alter_car_user_id_alter_carimage_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_cars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_of_cars', to='admin_portal.car'),
        ),
    ]
