# Generated by Django 4.2 on 2023-05-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0005_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
