# Generated by Django 4.2 on 2023-05-02 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0006_buyer_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
